mod/project.py, verbs/run.py
OS X / Linux / Windows: pass command line arguments to target with:
```
./fips run [target] [config] -- <list of arguments>
```
=> Optional command line arguments to 'fips run'

README.md, registry.yml
Add recast to registry. 
I've converted recast demo to glfw3 as I'd said it would be easier than get a fipsified SDL, but at the same time I've not tested on MacOS (I do not have one) or Windows (but will do soon).
Note: The glfw3 conversion is currently hosted at my fork, but the changes may get accepted upstream as the maintainer already confirmed it prefers glfw. I must only verify that premake4 builds correctly on MacOS and Windows before doing the PR there.
=> Add fips-recast to registry

cmake/fips.cmake, cmake/fips_generators.cmake, cmake/fips_private.cmake, mod/dep.py
Implements a proposal for issue #48 (and floooh/fips-bgfx#4):
- adds a fips_requires(target ...) that only creates a dependency link between current target from fips_begin/end_*() to the targets required. This can be used to force tools compilation before the current target build.
- changes fips_generate and fips_handle_generators to use required targets.
- changes generation build target from ALL_GENERATE to generate only for the targets that uses a fips_generate. Otherwise generators will happens only before anything else, but we want specify order via requires.
Bonus:
- fix .fips-gen.py generation when the project does not import anything.
- fix some trailing spaces (side-effect from my editing, sorry).
=> Proposal for #48

cmake-toolchains/linux.cmake, cmake/fips.cmake
Here's another "cross compile" flag. I'm not completely sure there isn't a more convenient option available, but it works.
=> Linux: added option to compile 32-bit builds on 64-bit hosts

mod/dep.py, mod/project.py, mod/tools/git.py, registry.yml, site/p060_imports.md
This fixes the issues discussed before, if the rev is specified it will not use the depth value. The branch can still be used though. A side effect is that now it is possible to also specify a depth in the import that will override the default of 10 if not specified.
The test for these changes depends on this PR https://github.com/floooh/fips-hello-world/pull/1 and in this new project https://github.com/fungos/fips-hello-dep3
=> Supports specifying a commit in import directives

cmake/fips.cmake, site/p050_cmakeguide.md
fips_files_ex() can basically do a fips_dir + fips_files with cmake globbing
expressions for what to include and what to exclude.
fips_src() is exactly the same but adding by default any file *.c, *.cc,
*.cpp, *.h, *.hh or *.hpp.
We can rename the functions if we find anything better.
Also note that I let some messages commented in the code to easy debugging in the short term. We can remove them if you do think it will be better too.
These two functions are needed for my incoming changes to fips-bgfx project.
=> Implements fips_files_ex() and fips_src().

.travis.yml, site/p050_cmakeguide.md
that we can use to add fips feature tests. Any target starting by 'test_'
will be ran automatically with testrunner.py, other targets are ignored.
Also fix a minor typo in the doc.
(fix tests, retry travis-ci)
=> Add project fips-tests on travis scripts, this is a reorganized project

mod/util.py
This matches any Cygwin version to be mapped as a Linux platform.
The cygwin platform identification normally should match the CYGWIN_NT-X
where X is the underlying Windows version. Tested this on Windows 10 with
Cygwin x86_64 and was able to build fips-hello-world project.
Closes #128
=> Add support to Cygwin

configs/win32-vs2017-debug.yml, configs/win32-vs2017-profiling.yml, configs/win32-vs2017-release.yml, configs/win32-vs2017-unittest.yml, configs/win64-vs2017-debug.yml, configs/win64-vs2017-profiling.yml, configs/win64-vs2017-release.yml, configs/win64-vs2017-unittest.yml, mod/config.py
This adds support for the 'Visual Studio 15' and 'Visual Studio 15 Win64' generators (available since cmake 3.7).
=> Add support for vs2017 generators

generators/genutil.py
A minor QoL issue. When writing codegen scripts, I noticed a Python error if I try to delete output file(s) to force a rebuild.
It works as expected after `fips clean` or when changing the script `Version`.
=> Check file exists before trying to parse version

cmake/fips.cmake, cmake/fips_private.cmake, site/p050_cmakeguide.md
Adds flag GROUP_FOLDERS to fips_files_ex to automatically generate groups reflecting file system folders of added files.
The GROUP_FOLDERS flag on fips_file_ex (and consequently fips_files) helps generating an ideal project group structure (eg. in a Visual Studio solution) when recursive glob is used. When doing, for example, `fips_files(. GROUP_FOLDERS)` will basically add all source files to the solution mapped exactly 
as the project folders structure on disk.
To implement this, one private helper function was needed where it iterates over a list of paths to files in the projet pushing each file to a group named after its path.
Adds this new feature documentation.
Removes some forgotten commented debug messages.
=> Adds flag GROUP_FOLDERS to fips_files_ex

cmake/fips.cmake, cmake/fips_private.cmake
Now this have the same generated result for both `fips_src(folder GROUP_FOLDERS)`  and from inside `folder` with `fips_src(. GROUP_FOLDERS)`.
=> This fixes the discussed issue with GROUP_FOLDERS

mod/config.py
Noticed that the list of configs isn't sorted anymore on Linux and MacOS. Outrageous!
=> sort output of ./fips list configs

cmake/fips.cmake, mod/config.py, mod/dep.py, mod/verb.py
Specifically for fips-configs, fips-toolchains, and fips-verbs logic.
=> Remove assumption that current project lies in the same dir as fips.

cmake-toolchains/windows.cmake, site/p050_cmakeguide.md
If FIPS_DYNAMIC_CRT is set, VS compiler will use /MD and /MDd instead /MT and /MTd for Windows/VS compilation. The default behavior is still MT.
This is required because setting one own project to use MD will not work if the project has any fips import as the imports will all be MT.
By setting FIPS_DYNAMIC_CRT before including fips.cmake every import will use the same runtime.
Fix a typo in the docs.
=> Makes it possible to switch to the dynamic CRT.

mod/tools/node.py
The 'out' var is a byte string, so it expects the same type as the argument to startwith.
=> Fix Python3 issue

mod/tools/vscode.py
Without these changes, the code throws exceptions on 'fips gen' running under Python 3
=> Update vscode.py with Python3 fixes

cmake-toolchains/emscripten.toolchain.cmake
This option is useful when an app may work with big amounts of data but still need to run on devices which are not likely to allocate big chunks of memory.
So it would be nice to have such an option in emscripten toolchain.
=> "Allow memory growth" option for emscripten toolchain.

mod/project.py, mod/tools/cmake.py
Passes the `num_jobs` parameter to cmake, just like the other build tools.
Also makes the output less verbose when compiling with msbuild. There's still that "CMake does not need to re-run because..." spam, but the only other/less verbose level is "quiet", which doesn't give _any_ progress indicator at all.
=> less verbose msbuild output, added num_jobs parameter

mod/markdeep.py
A minor observation with some 3rd party headers (SDL2), `/*#include <...>*/` was detected as start of a markdeep block.
It's still not idiot-proof with this change, e.g. `/*# define ...*/` still triggers. Probably not an issue though.
=> markdeep: improved comment block detection

cmake/fips.cmake, configs/linux-clion-debug.yml, configs/linux-clion-release.yml, configs/osx-clion-debug.yml, configs/osx-clion-release.yml, mod/config.py, mod/project.py, mod/tools/__init__.py, mod/tools/clion.py, verbs/clion.py, verbs/diag.py, verbs/open.py
I got me a personal license recently, so I looked into streamlining its use with fips. With this PR some minimal workspace configuration is written to `$project_dir/.idea/`, which is then nourished by CLion when the project is loaded.
I didn't bother to generate a complete workspace config, so there's some room for improvement:
- in the project browser, all _generated_ source files are put into the root folder
- CLion detects and adds run/debug configurations by itself, but `fips run` settings (cwd, arguments) are not yet considered
Other known issues:
- `fips open` (and `fips diag tools`) works on Linux by asking `snap`, which is used when installing from Ubuntu's "app store". It won't work when downloading and installing CLion manually. On OSX, it expects CLion to be installed in …
=> CLion IDE support

mod/dep.py
- projects with more than 3 modules will create a group with the project name inside imports
- imports can be added to a group in fips.yml
=> Enable grouping of imports

site/p010_getstarted.md
This adds a short paragraph to the Get Started section to explain setting up a new project with fips init. I wasn't able to preview the changes as I'm not really sure what the process is you go through to get the html out for the gh-pages branch. I think I got it right though :)
Happy to do a proper preview first if you enlighten me.
=> Add fips init to documentation

mod/tools/vscode.py
Generally I want my default quick action to be build and launch for quick iteration. I'd been tweaking the generated launch config, but it was getting annoying doing that every regen. This change will add 3 new launch tasks for each permutation of pre launch build and pause at entry.
=> launch task permutations for build and pause

.travis.yml, mod/tools/clion.py
Updated CLion detection in Linux to no longer require snap.  As long as "clion" or "clion.sh" are part of the system path, the detection will now pass.
=> Improving CLion detection in Linux

tools/android-create-apk.py
I don't know how well this plays with oryol but it should work fine with floooh/sokol#87.
I had a line of code for stripping dashes from package names as well but that seems to have been fixed in the master branch so I left it out.
=> Allow rotation in default Android manifest

cmake-toolchains/emscripten.toolchain.cmake
More info on embind: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html
And the emscripten modules: https://github.com/emscripten-core/emscripten/pull/3447
Btw, I've also fipsified a bunch of projects:
https://github.com/GeertArien/fips-libpng
https://github.com/GeertArien/fips-rapidjson
https://github.com/GeertArien/fips-tclap
https://github.com/GeertArien/fips-rapidxml
https://github.com/GeertArien/fips-clipper
Is there any procedure to follow to get them added to https://github.com/fips-libs ?
=> Add option for embind and enable emscripten cmake modules

cmake-toolchains/emscripten.toolchain.cmake
Sorry, in my last PR I didn't take into account that the emscripten-root variable had a recent name change, should've tested it better.
If you wan to test this yourself I created a very small test project: https://github.com/GeertArien/fips-endian-test
When generating one of the emscripten configs it should throw the following error or similar (only first run or after ./fips clean):
`CMake Error at /**/TestBigEndian.cmake:106 (message):
TEST_BIG_ENDIAN found no result!
Call Stack (most recent call first):
code/CMakeLists.txt:3 (test_big_endian)`
This PR should fix that.
=> Use correct cmake variable for emscripten root folder

mod/dep.py
I'm creating this PR as a follow-up to my rant on Twitter. It adds an option to `fips.yml` to export header paths based on CMake conditions, similar to the `cond` parameter for imports.
~~~
---
exports:
platform-header-dirs:
include: "FIPS_OSX"
include/SDL2: "FIPS_WINDOWS"
~~~
Naming and YML format are subject for discussion! ;)
=> option in fips.yml to conditionally export include paths

verbs/cache.py
I often find myself needing to open the CMakeCache, either to double-check variables, or just to modify something. Using the 'config' keyword works, but sometimes I don't really need to go through the cmake gui.
I added a simple verb that just opens the cmake cache file.
I understand if this is a bit redundant, but maybe someone will find it useful.
=> Added 'cache' verb that open CMakeCache with the default text editor

cmake/fips_private.cmake
Adding a file with fips_files(filname) will break on line 237 in fips_private.cmake if filename has no extension. This PR adds a check to see if the variable exists before comparing it.
You probably only expected source files to be added here. I'm using the code below to add my data resource files to a macOS app bundle. Your could perhaps use this code inside fips as well, but I wasn't sure exactly where to add this feature. 
CMakeList.txt somewhere:
```
if (FIPS_MACOS)
file(GLOB_RECURSE resources_data
"${CMAKE_CURRENT_SOURCE_DIR}/data/*"
)
endif()
```
Later inside fips_begin_app()
```
if (FIPS_MACOS)
fips_dir(.)
foreach(res_file ${resources_data})
fips_files(${res_file})
file(RELATIVE_PATH res_rel_path "${CMAKE_CURRENT_SOURCE_DIR}" ${res_file})
get_filename_component(res_path …
```
=> bugfix: files without extension will crash fips_files()

cmake/fips_private.cmake
Sorry for all the PR, but I don't want to make your code worse. I did some more research, and this is the proper solution that should work in all cmakes. 
```if (${f_ext} STREQUAL ".m")```
```if ("${f_ext}" STREQUAL ".m")```
expands to 
```if ( STREQUAL ".m")```
```if ("" STREQUAL ".m")```
when f_ext is the empty string. 
Complications in first case: If f_ext has a value of say "ext" _and_ there is a variable with name ext, cmake then takes the value of that variable into the if statement. If there isn't a variable named ext, ext is converted to the string "ext". So, adding "" around ${} is the safe way.
I'm mostly on very modern CMake versions btw, VS2019 is only supported in 3.15+
=> handle empty extension, better solution

mod/log.py, mod/tools/vscode.py
Log colors has always been wonky for me: GREEN and RED has worked, but no other colors.
I've changed the color codes, and it seems much more reliable now.
I've tested it in powershell, cmd, debian default terminal and afaik, it works fine.
edit: Also tested in both python 2 and 3
=> Fixed incorrect log colors + Improvements to generation time for VSCode on Windows

mod/tools/vscode.py, verbs/set.py
Adds an additional `fips set` option so fips generates fewer launch configs on `fips gen` when using vscode configurations. 
Can be set via `fips set vscode-launch-configs [all|minimal|skip_build]`
`minimal`: Only generates one launch config per executable which builds + runs.
`skip_build`: Generates the previous configs plus one that skips builds.
`all`: Keeps the current behaviour and the default still.
My python skills are non-existant so please let me know if there are things to clean up, happy to do so!
=> Options to generate fewer vscode launch configs

cmake/fips_private.cmake
There was a change in CMake behaviour in 3.20, see: https://cmake.org/cmake/help/latest/policy/CMP0119.html#policy:CMP0119
Your old fix will now force .m files to be compiled as C (instead of with the C compiler), which fails. I added a check based on your comment but I have not tested this on all CMake versions. I know it works on 3.20 with my changes. 
To test the new behaviour you need have CMake >= 3.20 installed and also to define:
`cmake_minimum_required(VERSION 3.20)
`
=> fix obj-c compile errors on cmake >= 3.20

cmake-toolchains/windows.cmake
The /MT /MD flags are not set correctly in CMake 3.15+. Maybe you want to do this in a different place, but this works.
See: https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY
=> Fix /MT /MD flags for Cmake 3.15+

verbs/build.py, verbs/make.py
Added a 'clean' option to 'fips build', there is one under 'fips make clean' but it wasn't in the help description. So, added that too. :)
Let me know what you think, I'm not 100% sure on syntax. Is there a way to grab all the configs currently generated? With this setup you can do 'fips build clean win64-vs*' and it will clean all VS builds. But you get an error if one doesn't exists.
=> build clean option, make clean help added

mod/tools/cmake.py
A quick fix for issue #273. Compilation is much faster without --parallel flag.
=> remove --parallel flag on windows builds

tools/android-create-apk.py
Fix the issue where setting android:exported="true" is required to start an Activity on Android 14
=> Fix the issue of inability to start on Android 14

mod/tools/cmake.py
I updated the cmake.check_exists function to check against cmake 3.21 as it is needed for lastest fips builds.
=> Updated the cmake.check_exists function

tools/android-create-apk.py
Add support for packing resources to apk copied into `assets` folder in Android project.
=> Android apk generator: add support for assets folder
